sas-core/main/default/objects/Knowledge__kav/fields/Confidential__c.field-meta.xml
<CustomField>
    <fullName>Confidential__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confidential</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Knowledge__kav/fields/Contentful_Id__c.field-meta.xml
<CustomField>
  <fullName>Contentful_Id__c</fullName>
  <label>Contentful Id</label>
  <length>255</length>
  <type>Text</type>
</CustomField>

sas-core/main/default/objects/Knowledge__kav/fields/FCS_SubType__c.field-meta.xml
<CustomField>
    <fullName>FCS_SubType__c</fullName>
    <label>Sub-type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FCS_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Allowances</fullName>
            </value>
            <value>
                <fullName>Allowances - hand baggage</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>Assistance</fullName>
            </value>
            <value>
                <fullName>Baggage general</fullName>
            </value>
            <value>
                <fullName>Cobranded with EuroBonus</fullName>
            </value>
            <value>
                <fullName>Dangerous Goods/Weapons</fullName>
            </value>
            <value>
                <fullName>Death of passenger or the passenger&apos;s immediate family - SAS</fullName>
            </value>
            <value>
                <fullName>Earning points</fullName>
            </value>
            <value>
                <fullName>EB Highlights/Error reports</fullName>
            </value>
            <value>
                <fullName>EuroBonus Program</fullName>
            </value>
            <value>
                <fullName>Excess baggage - Charge &amp; Keep</fullName>
            </value>
            <value>
                <fullName>Excess baggage - Charges</fullName>
            </value>
            <value>
                <fullName>Excess baggage - Prepaid XBAG</fullName>
            </value>
            <value>
                <fullName>Forbidden items in hand baggage</fullName>
            </value>
            <value>
                <fullName>Former Partners</fullName>
            </value>
            <value>
                <fullName>Form of Payment</fullName>
            </value>
            <value>
                <fullName>Form of Payment-Advanced</fullName>
            </value>
            <value>
                <fullName>Fragile and special value items</fullName>
            </value>
            <value>
                <fullName>Give Away Membership</fullName>
            </value>
            <value>
                <fullName>Hotel Partners</fullName>
            </value>
            <value>
                <fullName>IATA baggage resolution 302</fullName>
            </value>
            <value>
                <fullName>Life Time Gold</fullName>
            </value>
            <value>
                <fullName>Meals</fullName>
            </value>
            <value>
                <fullName>Meals - Advanced</fullName>
            </value>
            <value>
                <fullName>Medical</fullName>
            </value>
            <value>
                <fullName>Membership levels</fullName>
            </value>
            <value>
                <fullName>Minor</fullName>
            </value>
            <value>
                <fullName>Musical Instruments</fullName>
            </value>
            <value>
                <fullName>Name change and name correction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Knowledge__kav/fields/FCS_Type__c.field-meta.xml
<CustomField>
    <fullName>FCS_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EuroBonus</fullName>
            </value>
            <value>
                <fullName>Reservations</fullName>
            </value>
            <value>
                <fullName>Functional Product Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Knowledge__kav/fields/Searchable__c.field-meta.xml
<CustomField>
    <fullName>Searchable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Searchable</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/classes/services/KnowledgeService.cls
public without sharing class KnowledgeService {
  public static KnowledgeService newInstance() {
    return (KnowledgeService) SAS_Service_Application.Service.newInstance(
      KnowledgeService.class
    );
  }

  @future(callout=true)
  public static void initiateContentFetch() {
    KnowledgeJsonToApex contentfulContent = KnowledgeIntegrationService.fetchContentfulContent();
    processContentfulContent(contentfulContent);
  }

  public static void processContentfulContent(KnowledgeJsonToApex contentfulContent) {
    Map<String, KnowledgeJsonToApex.Item> contentfulContentMap = transformContentToMap(
      contentfulContent
    );

    Map<String, Knowledge__kav> existingKnowledges = getExistingKnowledges(
      contentfulContentMap.keySet()
    );

    if (!contentfulContentMap.isEmpty()) {
      Map<String, String> draftKnowledgesIds = createDraftKnowledges(
        contentfulContentMap,
        existingKnowledges
      );
      updateAndPublishKnowledges(draftKnowledgesIds, contentfulContentMap);
    }
  }

  public static Map<String, KnowledgeJsonToApex.Item> transformContentToMap(
    KnowledgeJsonToApex contentfulContent
  ) {
    Map<String, KnowledgeJsonToApex.Item> contentfulContentMap = new Map<String, KnowledgeJsonToApex.Item>();

    for (KnowledgeJsonToApex.Item item : contentfulContent.items) {
      contentfulContentMap.put(item.sys.id, item);
    }
    return contentfulContentMap;
  }

  public static Map<String, Knowledge__kav> getExistingKnowledges(
    Set<String> contentfulContentIds
  ) {
    Map<String, Knowledge__kav> knowledgesMap = new Map<String, Knowledge__kav>();

    List<Knowledge__kav> existingKnowledgesList = [
      SELECT Id, Contentful_Id__c, LastPublishedDate, KnowledgeArticleId
      FROM Knowledge__kav
      WHERE
        Contentful_Id__c IN :contentfulContentIds
        AND PublishStatus = 'Online'
    ];
    for (Knowledge__kav knowledge : existingKnowledgesList) {
      knowledgesMap.put(knowledge.Contentful_Id__c, knowledge);
    }

    return knowledgesMap;
  }

  public static Map<String, String> createDraftKnowledges(
    Map<String, KnowledgeJsonToApex.Item> contentfulContentMap,
    Map<String, Knowledge__kav> existingKnowledges
  ) {
    List<Knowledge__kav> newKnowledgesToCreate = new List<Knowledge__kav>();
    Map<String, String> draftKnowledgeIds = new Map<String, String>();

    for (String contentfulId : contentfulContentMap.keySet()) {
      KnowledgeJsonToApex.Item contentfulContent = contentfulContentMap.get(
        contentfulId
      );
      Knowledge__kav knowledgeArticle = existingKnowledges.get(contentfulId);
      Id draftKnowledgeId;

      if (knowledgeArticle == null) {        
        Knowledge__kav newKnowledgeArticle = new Knowledge__kav(
          Title = contentfulContent.fields.title == null
            ? contentfulContent.fields.id
            : contentfulContent.fields.title,
          UrlName = contentfulContent.fields.id,
          FCS_Body__c = contentfulContent.fields.body,
          FCS_Type__c = contentfulContent.fields.type,
          FCS_SubType__c = contentfulContent.fields.subType,
          Contentful_Id__c = contentfulContent.sys.id,
          Confidential__c = contentfulContent.fields.confidential == null
            ? false
            : contentfulContent.fields.confidential,
          Searchable__c = contentfulContent.fields.searchable == null
            ? true
            : contentfulContent.fields.searchable
        );
        newKnowledgesToCreate.add(newKnowledgeArticle);
      }
  
      if (
        knowledgeArticle != null &&
        contentfulContent.sys.updatedAt > knowledgeArticle.LastPublishedDate
      ) {
        draftKnowledgeId = KbManagement.PublishingService.editOnlineArticle(
          knowledgeArticle.KnowledgeArticleId,
          false
        );
        draftKnowledgeIds.put((String) draftKnowledgeId, contentfulId);
      }
    }

    insert newKnowledgesToCreate;

    for (Knowledge__kav newKnowledgeArticle : newKnowledgesToCreate) {
      draftKnowledgeIds.put(
        newKnowledgeArticle.Id,
        newKnowledgeArticle.Contentful_Id__c
      );
    }

    return draftKnowledgeIds;
  }

  public static void updateAndPublishKnowledges(
    Map<String, String> draftKnowledgeIds,
    Map<String, KnowledgeJsonToApex.Item> contentfulContentMap
  ) {
    List<Knowledge__kav> draftKnowledges = [
      SELECT
        Id,
        Title,
        FCS_Body__c,
        KnowledgeArticleId,
        UrlName,
        Contentful_Id__c
      FROM Knowledge__kav
      WHERE Id IN :draftKnowledgeIds.keySet()
    ];

    for (Knowledge__kav knowledgeArticle : draftKnowledges) {
      String contentfulId = draftKnowledgeIds.get(knowledgeArticle.Id);
      KnowledgeJsonToApex.Item contentfulContent = contentfulContentMap.get(
        contentfulId
      );

      knowledgeArticle.Title = contentfulContent.fields.title == null
        ? contentfulContent.fields.id
        : contentfulContent.fields.title;
        knowledgeArticle.UrlName = contentfulContent.fields.id;
        knowledgeArticle.FCS_Body__c = contentfulContent.fields.body;
        knowledgeArticle.FCS_Type__c = contentfulContent.fields.type;
        knowledgeArticle.FCS_SubType__c = contentfulContent.fields.subType;
        knowledgeArticle.Confidential__c = contentfulContent.fields.confidential == null
          ? false
          : contentfulContent.fields.confidential;
        knowledgeArticle.Searchable__c = contentfulContent.fields.searchable == null
          ? true
          : contentfulContent.fields.searchable;
    }

    update draftKnowledges;

    for (Knowledge__kav knowledgeArticle : draftKnowledges) {
      KbManagement.PublishingService.publishArticle(
        knowledgeArticle.KnowledgeArticleId,
        true
      );
    }
  }

  public static void deleteArticlesFromContentfulId(String contentfulId) {
    List<Knowledge__kav> knowledgeArticles = [SELECT Id, KnowledgeArticleId FROM Knowledge__kav WHERE Contentful_Id__c = :contentfulId AND PublishStatus = 'Online'];

    if (knowledgeArticles.isEmpty()) return;

    Knowledges.newInstance(knowledgeArticles).deletePublishedArticles();
  }
}