sas-core/main/default/objects/Case/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <complianceGroup>WipeRetain</complianceGroup>
    <description>The department responsible for this case</description>
    <inlineHelpText>The department responsible for this case</inlineHelpText>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agent Helpdesk</fullName>
            </value>
            <value>
                <fullName>Care</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Customer Claim</fullName>
            </value>
            <value>
                <fullName>Digital Channel Support</fullName>
            </value>
            <value>
                <fullName>Direct Sales</fullName>
            </value>
            <value>
                <fullName>Distribution</fullName>
            </value>
            <value>
                <fullName>EuroBonus</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>Functional Product Support</fullName>
            </value>
            <value>
                <fullName>Group Sales</fullName>
            </value>
            <value>
                <fullName>Info Hub</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Refunds</fullName>
            </value>
            <value>
                <fullName>Refunds OC KANA</fullName>
            </value>
            <value>
                <fullName>Sales Control BOM</fullName>
            </value>
            <value>
                <fullName>SAS Operating Center</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
                <isActive>false</isActive>
                <label>SME</label>
            </value>
            <value>
                <fullName>SoMe Support</fullName>
            </value>
            <value>
                <fullName>Telephony</fullName>
            </value>
            <value>
                <fullName>Vendor Management</fullName>
            </value>
             <value>
                <fullName>Charge Back</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/classes/invocableMethods/SendEmailForReadOnlyCase.cls
public with sharing class SendEmailForReadOnlyCase {
  @InvocableMethod(label='Send template email')
  public static void sendEmail(List<Id> caseIds) {
    List<Case> allCases = CasesSelector.newInstance()
      .selectById(new Set<Id>{ caseIds[0] });

    String splitEmailAddress = allCases[0].SuppliedEmail.substringBefore('@');

    List<EmailServicesAddress> emailServiceAddress = [
      SELECT Id, LocalPart
      FROM EmailServicesAddress
      WHERE LocalPart = :splitEmailAddress
    ];

    if (!emailServiceAddress.isEmpty()) {
      return;
    }

    String closedCasePermanentlyTemplate = Cases.allReadOnlyConfigs.get(
      allCases[0].Department__c
    ).Email_Template_Name__c;
    fflib_ISObjectUnitOfWork uow = SAS_Service_Application.UnitOfWork.newInstance();
    Messaging.SingleEmailMessage msg = EmailMessages.createSingleEmailMessageFromTemplate(
      closedCasePermanentlyTemplate,
      caseIds[0]
    );
    msg.SetReplyTo('no-reply@flysas.com');
    Cases.newInstance(allCases).emailOwner(msg, uow);

    uow.commitWork();
  }
}