sas-core/main/default/objects/LIA_Claim__c/fields/EU261_Handling_Status__c.field-meta.xml
<CustomField>
    <fullName>EU261_Handling_Status__c</fullName>
    <inlineHelpText>Result of the automatic EU261 automation evaluation. 
Please review email conversation before start handling the case.</inlineHelpText>
    <label>EU261 Handling Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Eligible for compensation</fullName>
            </value>
            <value>
                <fullName>Ineligible for compensation</fullName>
            </value>
            <value>
                <fullName>Ineligible for compensation and expenses</fullName>
            </value>
            <value>
                <fullName>Ineligible for compensation but eligible for reimbursement</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Possibly eligible for compensation</fullName>
            </value>
            <value>
                <fullName>Unable to handle</fullName>
            </value>
            <value>
                <fullName>Unhandled</fullName>
                <default>true</default>
                <label>Unhandled</label>
            </value>
            <value>
                <fullName>Will not handle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/classes/batchables/RouteAutomationStuckCasesBatchable.cls
public with sharing class RouteAutomationStuckCasesBatchable implements Database.Batchable<LIA_Claim__c>, Database.AllowsCallouts, Database.Stateful {
  private Set<Id> caseIdsToManualHandling;

  public RouteAutomationStuckCasesBatchable() {
    this.caseIdsToManualHandling = new Set<Id>();
  }

  public Iterable<LIA_Claim__c> start(Database.BatchableContext jobId) {
    ClaimsSelector cl = ClaimsSelector.newInstance();
    List<LIA_Claim__c> claimsStuckFetchingData = cl.selectStuckUnhandledEU261ClaimsByDataStatus(
      'In Progress'
    );
    List<LIA_Claim__c> otherStuckClaims = cl.selectStuckEU261Claims();

    claimsStuckFetchingData.addAll(otherStuckClaims);
    return claimsStuckFetchingData;
  }

  public void execute(
    Database.BatchableContext bc,
    List<LIA_Claim__c> claimsToFetch
  ) {
    fflib_ISObjectUnitOfWork uowUpsert = SAS_Service_Application.UnitOfWork.newInstance();

    for (LIA_Claim__c c : claimsToFetch) {
      c.EU261_Handling_Status__c = 'Unable to handle';
      c.External_Data_Status__c = 'Unavailable';
      uowUpsert.registerDirty(c);
      caseIdsToManualHandling.add(c.Case__c);
    }
    uowUpsert.commitWork();
  }

  public void finish(Database.BatchableContext jobId) {
    if (caseIdsToManualHandling.size() > 0) {
      CaseService.assignPriorityAndRouteToQueue(caseIdsToManualHandling);
    }
  }
}