sas-core/main/default/objects/LIA_Claim__c/fields/EU261_Handling_Status__c.field-meta.xml
<CustomField>
    <fullName>EU261_Handling_Status__c</fullName>
    <inlineHelpText>Result of the automatic EU261 automation evaluation. 
Please review email conversation before start handling the case.</inlineHelpText>
    <label>EU261 Handling Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Eligible for compensation</fullName>
            </value>
            <value>
                <fullName>Ineligible for compensation</fullName>
            </value>
            <value>
                <fullName>Ineligible for compensation and expenses</fullName>
            </value>
            <value>
                <fullName>Ineligible for compensation but eligible for reimbursement</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Possibly eligible for compensation</fullName>
            </value>
            <value>
                <fullName>Unable to handle</fullName>
            </value>
            <value>
                <fullName>Unhandled</fullName>
                <default>true</default>
                <label>Unhandled</label>
            </value>
            <value>
                <fullName>Will not handle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/LIA_Claim__c/fields/Liability_PNR__c.field-meta.xml
<CustomField>
    <fullName>Liability_PNR__c</fullName>
    <description>PNR related to the Liability Claim</description>
    <label>PNR</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/batchables/FetchEDWBookingsForEU261ClaimsBatch.cls
public with sharing class FetchEDWBookingsForEU261ClaimsBatch implements Database.Batchable<LIA_Claim__c>, Database.AllowsCallouts, Database.Stateful {
  private static final Decimal MAX_RETRIEVE_COUNT = 3.0;
  private Set<Id> caseIdsToManualHandling;
  private Set<String> attemptedPNR;

  public FetchEDWBookingsForEU261ClaimsBatch() {
    this.caseIdsToManualHandling = new Set<Id>();
    this.attemptedPNR = new Set<String>();
  }

  public Iterable<LIA_Claim__c> start(Database.BatchableContext jobId) {
    return ClaimsSelector.newInstance()
      .selectUnhandledEU261ClaimsByDataStatus('In Progress');
  }

  public void execute(
    Database.BatchableContext bc,
    List<LIA_Claim__c> claimsToFetch
  ) {
    fflib_ISObjectUnitOfWork uow = SAS_Service_Application.UnitOfWork.newInstance();

    Set<String> bookingReferences = new Set<String>();
    Set<String> retrievedPNR = new Set<String>();
    for (LIA_Claim__c c : claimsToFetch) {
      if (this.attemptedPNR.contains(c.Liability_PNR__c)) {
        continue;
      }
      bookingReferences.add(c.Liability_PNR__c);
    }

    Bookings bInstance = BookingService.fetchEDWBookingsByBookingReferences(
      bookingReferences
    );
    this.attemptedPNR.addAll(bookingReferences);
    if (bInstance.objects != null) {
      for (Booking b : bInstance.objects) {
        retrievedPNR.add(b.bookingReference);
      }
    }

    for (LIA_Claim__c c : claimsToFetch) {
      Boolean foundBooking = retrievedPNR.contains(c.Liability_PNR__c);
      Decimal newRetrieveCount = c.External_Data_Retrieve_Count__c + 1;
      if (foundBooking) {
        c.External_Data_Status__c = 'Completed';
      } else {
        if (newRetrieveCount > MAX_RETRIEVE_COUNT) {
          c.EU261_Handling_Status__c = 'Unable to handle';
          c.External_Data_Status__c = 'Unavailable';
          caseIdsToManualHandling.add(c.Case__c);
        }
      }
      c.External_Data_Retrieve_Count__c = newRetrieveCount;
      uow.registerDirty(c);
    }
    uow.commitWork();
  }

  public void finish(Database.BatchableContext jobId) {
    if (caseIdsToManualHandling.size() > 0) {
      CaseService.assignPriorityAndRouteToQueue(caseIdsToManualHandling);
    }
  }
}