sas-core/main/default/objects/EBVoucherPaymentApproved__e/EBVoucherPaymentApproved__e.object-meta.xml
<CustomObject>
    <description>This event is dispatched whenever a eurobonus or voucher payment is approved.</description>
    <label>EBVoucherPaymentApproved</label>
    <pluralLabel>EBVoucherPaymentApproved</pluralLabel>
</CustomObject>

sas-core/main/default/objects/EBVoucherPaymentApproved__e/fields/Settlement__c.field-meta.xml
<CustomField>
    <fullName>Settlement__c</fullName>
    <description>The Id of the Eurobonus or voucher settlement to process.</description>
    <label>Settlement</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/domain/EBVoucherPaymentApproved.cls
public without sharing class EBVoucherPaymentApproved extends ApplicationDomain {
  public EBVoucherPaymentApproved(List<SObject> records) {
    super(records);
    this.instanceRecords = (List<EBVoucherPaymentApproved__e>) Records;
  }

  public class Constructor implements fflib_SObjectDomain.IConstructable {
    public fflib_SObjectDomain construct(List<SObject> records) {
      return new EBVoucherPaymentApproved(records);
    }
  }

  public static EBVoucherPaymentApproved newInstance(
    List<EBVoucherPaymentApproved__e> sObjectList
  ) {
    return (EBVoucherPaymentApproved) SAS_Service_Application.Domain.newInstance(
      sObjectList
    );
  }

  public List<EBVoucherPaymentApproved__e> instanceRecords;

  public override void onAfterInsert() {
    for (EBVoucherPaymentApproved__e event : instanceRecords) {
      SettlementService.processPayableSettlement(event.Settlement__c);
    }
  }
}