sas-core/main/default/objects/Automated_Message_Outbound__mdt/Automated_Message_Outbound__mdt.object-meta.xml
<CustomObject>
    <label>IRR Automated Message Outbound</label>
    <pluralLabel>IRR Automated Message Outbounds</pluralLabel>
</CustomObject>

sas-core/main/default/objects/Automated_Message_Outbound__mdt/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Automated_Message_Outbound__mdt/fields/Days_Before_Comm_Need_to_Send__c.field-meta.xml
<CustomField>
    <fullName>Days_Before_Comm_Need_to_Send__c</fullName>
    <label>Days Before Comm Need to Send</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/Automated_Message_Outbound__mdt/fields/Is_Send_Email__c.field-meta.xml
<CustomField>
    <fullName>Is_Send_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Send Email</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Automated_Message_Outbound__mdt/fields/Is_Send_SMS__c.field-meta.xml
<CustomField>
    <fullName>Is_Send_SMS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Send SMS</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Automated_Message_Outbound__mdt/fields/Outbound_Station_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Station_Arrival__c</fullName>
    <label>Outbound Station Arrival</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Automated_Message_Outbound__mdt/fields/Outbound_Station_Departure__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Station_Departure__c</fullName>
    <label>Outbound Station Departure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Automated_Message_Outbound__mdt/fields/Sms_Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Sms_Template_Name__c</fullName>
    <label>SmsTemplate Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Automated_Message_Outbound__mdt/fields/Station_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Station_Arrival__c</fullName>
    <label>Station Arrival</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Automated_Message_Outbound__mdt/fields/Station_Departure__c.field-meta.xml
<CustomField>
    <fullName>Station_Departure__c</fullName>
    <label>Station Departure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Automated_Message_Outbound__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
                <default>true</default>
                <label>Current</label>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/classes/IRR_SEL_AutomatedMessageSelector.cls
/**
* @author Gaurav, Coforge
* @date 2024
*
* @description Selector class for the IRR Automated Message metadata object.
*/
public class IRR_SEL_AutomatedMessageSelector extends fflib_SObjectSelector implements IRR_SEL_IAutomatedMessageSelector  {
    public static IRR_SEL_IAutomatedMessageSelector newInstance() 
    {

        return (IRR_SEL_IAutomatedMessageSelector) IRR_Application.Selector.newInstance(
            Automated_Message_Outbound__mdt.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList() 
    {

        return new List<Schema.SObjectField> 
        { 

            Automated_Message_Outbound__mdt.DeveloperName,
            Automated_Message_Outbound__mdt.MasterLabel,
            Automated_Message_Outbound__mdt.Days_Before_Comm_Need_to_Send__c ,
            Automated_Message_Outbound__mdt.Comment__c,
            Automated_Message_Outbound__mdt.Is_Active__c,
            Automated_Message_Outbound__mdt.Is_Send_Email__c,
            Automated_Message_Outbound__mdt.Is_Send_SMS__c,
            Automated_Message_Outbound__mdt.Type__c,
            Automated_Message_Outbound__mdt.Station_Arrival__c,
            Automated_Message_Outbound__mdt.Station_Departure__c,
            Automated_Message_Outbound__mdt.Outbound_Station_Arrival__c,
            Automated_Message_Outbound__mdt.Outbound_Station_Departure__c,
            Automated_Message_Outbound__mdt.Email_Template_Name__c,
            Automated_Message_Outbound__mdt.Sms_Template_Name__c

           


        };

    }

    public Schema.SObjectType getSObjectType() {

        return Automated_Message_Outbound__mdt.SobjectType ;
    }

    public Database.QueryLocator getAutomatedMessage(){
        Boolean isActive =true;
        fflib_QueryFactory queryFactory = newQueryFactory()
        .setCondition('Is_Active__c =: isActive');
         return Database.getQueryLocator(queryFactory.toSOQL());
               
    }
}