sas-core/main/default/objects/IRR_Constant__mdt/IRR_Constant__mdt.object-meta.xml
<CustomObject>
    <label>Constant</label>
    <pluralLabel>Constant</pluralLabel>
</CustomObject>

sas-core/main/default/objects/IRR_Constant__mdt/fields/AIRLINE__c.field-meta.xml
<CustomField>
    <fullName>AIRLINE__c</fullName>
    <label>AIRLINE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_Constant__mdt/fields/ERROR_BOOKING_ID__c.field-meta.xml
<CustomField>
    <fullName>ERROR_BOOKING_ID__c</fullName>
    <label>ERROR_BOOKING_ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_Constant__mdt/fields/ERROR_BOOKING_REF__c.field-meta.xml
<CustomField>
    <fullName>ERROR_BOOKING_REF__c</fullName>
    <label>ERROR_BOOKING_REF</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_Constant__mdt/fields/ERROR_DELAY_MINUTES__c.field-meta.xml
<CustomField>
    <fullName>ERROR_DELAY_MINUTES__c</fullName>
    <label>ERROR_DELAY_MINUTES</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_Constant__mdt/fields/ERROR_DEPT_TIME__c.field-meta.xml
<CustomField>
    <fullName>ERROR_DEPT_TIME__c</fullName>
    <label>ERROR_DEPT_TIME</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_Constant__mdt/fields/ERROR_FLIGHT_ID__c.field-meta.xml
<CustomField>
    <fullName>ERROR_FLIGHT_ID__c</fullName>
    <label>ERROR_FLIGHT_ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_Constant__mdt/fields/ERROR_NEW_INFO_TIME__c.field-meta.xml
<CustomField>
    <fullName>ERROR_NEW_INFO_TIME__c</fullName>
    <label>ERROR_NEW_INFO_TIME</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_Constant__mdt/fields/ERROR_NO_ADDED_SEGMENTS__c.field-meta.xml
<CustomField>
    <fullName>ERROR_NO_ADDED_SEGMENTS__c</fullName>
    <label>ERROR_NO_ADDED_SEGMENTS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_Constant__mdt/fields/ERROR_NO_EVENT__c.field-meta.xml
<CustomField>
    <fullName>ERROR_NO_EVENT__c</fullName>
    <label>ERROR NO EVENT</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_Constant__mdt/fields/ERROR_NO_EVENT_TIME__c.field-meta.xml
<CustomField>
    <fullName>ERROR_NO_EVENT_TIME__c</fullName>
    <label>ERROR_NO_EVENT_TIME</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_Constant__mdt/fields/ERROR_SCHD_TIME__c.field-meta.xml
<CustomField>
    <fullName>ERROR_SCHD_TIME__c</fullName>
    <label>ERROR_SCHD_TIME</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_Constant__mdt/fields/EVENT_FLOW_NAME__c.field-meta.xml
<CustomField>
    <fullName>EVENT_FLOW_NAME__c</fullName>
    <label>EVENT_FLOW_NAME</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/IRR_SEL_ConstantSelector.cls
/**
* @author Gaurav Singh, Coforge
* @date 2024
*
* @description Selector class for the IRR constant metadata object.
*/

public class IRR_SEL_ConstantSelector extends fflib_SObjectSelector implements IRR_SEL_IConstantSelector  {
    
    public static IRR_SEL_IConstantSelector newInstance() 
    {

        return (IRR_SEL_IConstantSelector) IRR_Application.Selector.newInstance(
            IRR_Constant__mdt.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList() 
    {

        return new List<Schema.SObjectField> 
        { 

            IRR_Constant__mdt.DeveloperName,
            IRR_Constant__mdt.MasterLabel,
            IRR_Constant__mdt.AIRLINE__c,
            IRR_Constant__mdt.ERROR_BOOKING_ID__c,
            IRR_Constant__mdt.ERROR_BOOKING_REF__c,
            IRR_Constant__mdt.ERROR_DELAY_MINUTES__c,
            IRR_Constant__mdt.ERROR_DEPT_TIME__c,
            IRR_Constant__mdt.ERROR_FLIGHT_ID__c,
            IRR_Constant__mdt.ERROR_NEW_INFO_TIME__c,
            IRR_Constant__mdt.ERROR_NO_ADDED_SEGMENTS__c,
            IRR_Constant__mdt.ERROR_NO_EVENT_TIME__c,
            IRR_Constant__mdt.ERROR_SCHD_TIME__c,
            IRR_Constant__mdt.ERROR_NO_EVENT__c,
            IRR_Constant__mdt.EVENT_FLOW_NAME__c

        };

    }

    public Schema.SObjectType getSObjectType() {

        return IRR_Constant__mdt.SobjectType ;
    }

    public List<IRR_Constant__mdt> getEventContant(String eventName){


        fflib_QueryFactory queryFactory = newQueryFactory()
        .setCondition('DeveloperName =:eventName');
        List<IRR_Constant__mdt> constantMetadata = Database.query(queryFactory.toSOQL());
        return constantMetadata;
    }
               
}