sas-core/main/default/objects/IRR_LoungeAccessQRCode__c/IRR_LoungeAccessQRCode__c.object-meta.xml
<CustomObject>
    <label>Lounge Access QR Code</label>
    <nameField>
        <displayFormat>QR-{0000000000}</displayFormat>
        <label>Lounge Access QR Code  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lounge Access QR Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sas-core/main/default/objects/IRR_LoungeAccessQRCode__c/fields/expiryDate__c.field-meta.xml
<CustomField>
    <fullName>expiryDate__c</fullName>
    <label>expiry Date</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_LoungeAccessQRCode__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/IRR_LoungeAccessQRCode__c/fields/voucher_Code__c.field-meta.xml
<CustomField>
    <fullName>voucher_Code__c</fullName>
    <label>voucher Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/classes/IRR_SEL_LoungeAccessQRCodeSelector.cls
/**
* @author Ragbirendra Upadhyay, CoforgeTech
* @date 2023
*
*/
public class IRR_SEL_LoungeAccessQRCodeSelector extends fflib_SObjectSelector
implements IRR_SEL_ILoungeAccessQRCodeSelector {
    public static IRR_SEL_ILoungeAccessQRCodeSelector newInstance() {
        return (IRR_SEL_ILoungeAccessQRCodeSelector)
            IRR_Application.Selector.newInstance(IRR_LoungeAccessQRCode__c.SObjectType);
    }
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>
        {
            IRR_LoungeAccessQRCode__c.Id,
            IRR_LoungeAccessQRCode__c.expiryDate__c,
            IRR_LoungeAccessQRCode__c.voucher_Code__c,
            IRR_LoungeAccessQRCode__c.Status__c
        };
    } 
    public Schema.SObjectType getSObjectType() {
        return IRR_LoungeAccessQRCode__c.SObjectType;
    }
   
    public List<IRR_LoungeAccessQRCode__c> getActiveQR(Integer recordCount) {
        String status = 'Active';
        fflib_QueryFactory queryFactory = newQueryFactory()
            .setCondition('Status__c = :status')
            .setLimit(recordCount);
        List<IRR_LoungeAccessQRCode__c> loungeQRList = Database.query(queryFactory.toSOQL());
        return loungeQRList;   
    }
    public List<IRR_LoungeAccessQRCode__c> getActiveQR() {
        String status = 'Active';
        fflib_QueryFactory queryFactory = newQueryFactory()
            .setCondition('Status__c = :status');
        List<IRR_LoungeAccessQRCode__c> loungeQRList = Database.query(queryFactory.toSOQL());
        return loungeQRList;   
    }
    public List<AggregateResult> selectActiveRecordCount(){ 
     List<AggregateResult> result = [Select expiryDate__c, count(Id) totalCount From IRR_LoungeAccessQRCode__c where Status__c = 'Active'  Group by expiryDate__c ];
     
     system.debug('count:::'+result[0].get('totalCount'));
        return result;
    }
    
}