sas-core/main/default/objects/IRR_Manual_Icoupon_Voucher__mdt/IRR_Manual_Icoupon_Voucher__mdt.object-meta.xml
<CustomObject>
    <label>Manual Icoupon Voucher</label>
    <pluralLabel>Manual Icoupon Vouchers</pluralLabel>
</CustomObject>

sas-core/main/default/objects/IRR_Manual_Icoupon_Voucher__mdt/fields/IRR_Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>IRR_Currency_Code__c</fullName>
    <label>IRR Currency Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EUR</fullName>
                <default>true</default>
                <label>EUR</label>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>KR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>ISK</fullName>
            </value>
            <value>
                <fullName>NOK</fullName>
            </value>
            <value>
                <fullName>SEK</fullName>
            </value>
            <value>
                <fullName>CZK</fullName>
            </value>
            <value>
                <fullName>DKK</fullName>
            </value>
            <value>
                <fullName>LEK</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>HUF</fullName>
            </value>
            <value>
                <fullName>PLN</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/IRR_Manual_Icoupon_Voucher__mdt/fields/IRR_Reason_Comment__c.field-meta.xml
<CustomField>
    <fullName>IRR_Reason_Comment__c</fullName>
    <label>Reason Comment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_Manual_Icoupon_Voucher__mdt/fields/IRR_Voucher_Amount__c.field-meta.xml
<CustomField>
    <fullName>IRR_Voucher_Amount__c</fullName>
    <label>IRR Voucher Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/IRR_Manual_Icoupon_Voucher__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Currency</fullName>
                <default>true</default>
                <label>Currency</label>
            </value>
            <value>
                <fullName>Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/classes/IRR_SEL_ManualIcouponVoucherSelector.cls
public class IRR_SEL_ManualIcouponVoucherSelector extends fflib_SObjectSelector implements IRR_SEL_IManualIcouponVoucherSelector  {
    
    public static IRR_SEL_IManualIcouponVoucherSelector newInstance() 
    {

        return (IRR_SEL_IManualIcouponVoucherSelector) IRR_Application.Selector.newInstance(
            IRR_Manual_Icoupon_Voucher__mdt.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList() 
    {

        return new List<Schema.SObjectField> 
        { 

            IRR_Manual_Icoupon_Voucher__mdt.DeveloperName,
            IRR_Manual_Icoupon_Voucher__mdt.MasterLabel,
            IRR_Manual_Icoupon_Voucher__mdt.IRR_Currency_Code__c,
            IRR_Manual_Icoupon_Voucher__mdt.IRR_Voucher_Amount__c,
            IRR_Manual_Icoupon_Voucher__mdt.IRR_Reason_Comment__c,
            IRR_Manual_Icoupon_Voucher__mdt.Type__c

        };

    }

    public Schema.SObjectType getSObjectType() {

        return IRR_Manual_Icoupon_Voucher__mdt.SobjectType ;
    }

    public List<IRR_Manual_Icoupon_Voucher__mdt> getManualIcouponVoucher(){

         return Database.query(newQueryFactory().toSOQL());
               
    }

}