sas-core/main/default/objects/IRR_Standalone_Icoupon_Voucher__mdt/IRR_Standalone_Icoupon_Voucher__mdt.object-meta.xml
<CustomObject>
    <label>Standalone ICoupon Voucher</label>
    <pluralLabel>Standalone ICoupon Vouchers</pluralLabel>
</CustomObject>

sas-core/main/default/objects/IRR_Standalone_Icoupon_Voucher__mdt/fields/IRR_Airport_List__c.field-meta.xml
<CustomField>
    <fullName>IRR_Airport_List__c</fullName>
    <label>IRR_Airport_List</label>
    <type>TextArea</type>
</CustomField>

sas-core/main/default/objects/IRR_Standalone_Icoupon_Voucher__mdt/fields/IRR_Reason__c.field-meta.xml
<CustomField>
    <fullName>IRR_Reason__c</fullName>
    <label>IRR_Reason</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_Standalone_Icoupon_Voucher__mdt/fields/IRR_Voucher_Amount__c.field-meta.xml
<CustomField>
    <fullName>IRR_Voucher_Amount__c</fullName>
    <label>IRR_Voucher_Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/objects/IRR_Standalone_Icoupon_Voucher__mdt/fields/IRR_Voucher_Currency__c.field-meta.xml
<CustomField>
    <fullName>IRR_Voucher_Currency__c</fullName>
    <label>IRR_Voucher_Currency</label>
    <length>28</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_Standalone_Icoupon_Voucher__mdt/fields/IRR_Voucher_Profile__c.field-meta.xml
<CustomField>
    <fullName>IRR_Voucher_Profile__c</fullName>
    <label>IRR_Voucher_Profile</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/IRR_Standalone_Icoupon_Voucher__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Voucher</fullName>
                <default>true</default>
                <label>Voucher</label>
            </value>
            <value>
                <fullName>Reason</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/objects/IRR_Standalone_Icoupon_Voucher__mdt/fields/UniqueID__c.field-meta.xml
<CustomField>
    <fullName>UniqueID__c</fullName>
    <description>This is the voucher or reason ID to be sent to ICoupon</description>
    <label>UniqueID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sas-core/main/default/classes/IRR_SEL_StandaloneICouponSelector.cls
/**
* @author Rati Mehra, Coforge
* @date 2024
* @purpose Selector class to load the metadata of Standalone iCoupon Voucher
*/
public class IRR_SEL_StandaloneICouponSelector extends fflib_SObjectSelector implements IRR_SEL_IStandaloneIcouponSelector{
    
    public static IRR_SEL_IStandaloneICouponSelector newInstance() {

        return (IRR_SEL_IStandaloneIcouponSelector) IRR_Application.Selector.newInstance(
            IRR_Standalone_Icoupon_Voucher__mdt.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList() 
    {

        return new List<Schema.SObjectField> 
        { 

            IRR_Standalone_Icoupon_Voucher__mdt.IRR_Airport_List__c,
            IRR_Standalone_Icoupon_Voucher__mdt.IRR_Voucher_Profile__c,
            IRR_Standalone_Icoupon_Voucher__mdt.IRR_Reason__c,
            IRR_Standalone_Icoupon_Voucher__mdt.Type__c,
            IRR_Standalone_Icoupon_Voucher__mdt.UniqueID__c,
            IRR_Standalone_Icoupon_Voucher__mdt.IRR_Voucher_Amount__c,
            IRR_Standalone_Icoupon_Voucher__mdt.IRR_Voucher_Currency__c

        };

    }

    public Schema.SObjectType getSObjectType() {

        return IRR_Standalone_Icoupon_Voucher__mdt.SobjectType ;
    }

    public List<IRR_Standalone_Icoupon_Voucher__mdt> getStandaloneICouponVoucher(){

        return Database.query(newQueryFactory().toSOQL());
              
   }

}