sas-core/main/default/objects/Proactivity__c/fields/Automate_Matching_Claims__c.field-meta.xml
<CustomField>
    <fullName>Automate_Matching_Claims__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Automate any claims where the root cause is a flight which matches this proactivity</description>
    <inlineHelpText>Automate any claims where the root cause is a flight which matches this proactivity</inlineHelpText>
    <label>Automate Matching Claims</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Proactivity__c/fields/Eligibility_Explanation__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Explanation__c</fullName>
    <description>The explanation which will be presented to the user in a response email. Will occur in a setnance like &quot;...the flight was delayed/cancelled due to EXPLANATION. This is an event outside SAS control...&quot;. This explanation will only appear in emails where the customer&apos;s claim is denied.</description>
    <inlineHelpText>The explanation which will be presented to the user in a response email. Will occur in a setnance like &quot;...the flight was delayed/cancelled due to EXPLANATION. This is an event outside SAS control...&quot;. This explanation will only appear in emails where the customer&apos;s claim is denied.</inlineHelpText>
    <label>Eligibility Explanation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Proactivity__c/fields/EU261_Eligibility__c.field-meta.xml
<CustomField>
    <fullName>EU261_Eligibility__c</fullName>
    <defaultValue>&quot;Tentative&quot;</defaultValue>
    <description>Whether or not a claim with a &quot;root cause&quot;-flight which matches this proactivity should be eligible or not for EU261 compensation.</description>
    <inlineHelpText>Whether or not a claim with a &quot;root cause&quot;-flight which matches this proactivity should be eligible or not for EU261 compensation.</inlineHelpText>
    <label>EU261 Eligibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EU261_Eligibility</valueSetName>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Proactivity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>For differentiating between the different types of proactivities</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Major Event</fullName>
            </value>
            <value>
                <fullName>Automatically Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/globalValueSets/EU261_Eligibility.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Tentative</fullName>
        <default>true</default>
        <label>Tentative</label>
    </customValue>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <description>Whether or not a passenger is, is not or might be eligible for EU261 compensation.</description>
    <masterLabel>EU261 Eligibility</masterLabel>
</GlobalValueSet>

sas-core/main/default/classes/services/ProactivityService.cls
public without sharing class ProactivityService {
  public static ProactivityService newInstance() {
    return (ProactivityService) SAS_Service_Application.Service.newInstance(
      ProactivityService.class
    );
  }

  public static void createAutomationProactivitiesFromFlightIds(
    Set<Id> flightIds
  ) {
    List<Flight__c> flights = FlightsSelector.newInstance()
      .selectById(flightIds);
    List<FlightIrregularities__c> allIrregularities = FlightIrregularitiesSelector.newInstance()
      .selectByFlightId(flightIds);

    Map<Id, List<FlightIrregularities__c>> flightToIrregularities = new FlightIrregularities(
        allIrregularities
      )
      .getFlightIdToIrregularities();

    Set<Flight> flightObjects = new Set<Flight>();
    for (Flight__c f : flights) {
      List<FlightIrregularities__c> irrs = flightToIrregularities.get(f.Id);
      List<FlightIrregularity> irrObjects = new List<FlightIrregularity>();
      for (FlightIrregularities__c irr : irrs) {
        irrObjects.add(new FlightIrregularity(irr));
      }

      Flight fl = new Flight(f);
      fl.irregularities = irrObjects;
      flightObjects.add(fl);
    }

    createAutomationProactivities(flightObjects);
  }

  private static void createAutomationProactivities(Set<Flight> flights) {
    List<Proactivity__c> toInsert = new List<Proactivity__c>();
    for (Flight f : flights) {
      Proactivity__c p = createFromFlightWithIrregularity(f);
      if (p != null) {
        toInsert.add(p);
      }
    }

    if (toInsert.size() > 0) {
      insert toInsert;
    }
  }

  /**
   * Creates an automation proactivity if possible, otherwise returns null
   */
  private static Proactivity__c createFromFlightWithIrregularity(Flight f) {
    // If there are more than one irregularity, we cannot be sure what the
    // root cause is.
    if (f.irregularities.size() != 1) {
      return null;
    }

    FlightIrregularity fi = f.irregularities[0];
    if (fi.code == null || fi.reason == null) {
      return null;
    }
    fi.setEligibility(); // If not already set

    if (fi.description == null || fi.eligibleForEU261 == null) {
      return null;
    }

    Proactivity__c p = new Proactivity__c();
    p.Flight_Id__c = Flight.TEDSIdToSimpleFlightIds(f.tedsIdentifier)[0];
    p.Type__c = 'Automatically Created';
    p.Automate_Matching_Claims__c = false; // This is done on-demand in the irregularity
    p.Note__c = fi.description;
    p.Eligibility_Explanation__c = fi.description;
    p.EU261_Eligibility__c = fi.eligibleForEU261.name();

    return p;
  }
}