sas-core/main/default/objects/Proactivity__c/fields/Automate_Matching_Claims__c.field-meta.xml
<CustomField>
    <fullName>Automate_Matching_Claims__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Automate any claims where the root cause is a flight which matches this proactivity</description>
    <inlineHelpText>Automate any claims where the root cause is a flight which matches this proactivity</inlineHelpText>
    <label>Automate Matching Claims</label>
    <type>Checkbox</type>
</CustomField>

sas-core/main/default/objects/Proactivity__c/fields/Eligibility_Explanation__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Explanation__c</fullName>
    <description>The explanation which will be presented to the user in a response email. Will occur in a setnance like &quot;...the flight was delayed/cancelled due to EXPLANATION. This is an event outside SAS control...&quot;. This explanation will only appear in emails where the customer&apos;s claim is denied.</description>
    <inlineHelpText>The explanation which will be presented to the user in a response email. Will occur in a setnance like &quot;...the flight was delayed/cancelled due to EXPLANATION. This is an event outside SAS control...&quot;. This explanation will only appear in emails where the customer&apos;s claim is denied.</inlineHelpText>
    <label>Eligibility Explanation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sas-core/main/default/objects/Proactivity__c/fields/EU261_Eligibility__c.field-meta.xml
<CustomField>
    <fullName>EU261_Eligibility__c</fullName>
    <defaultValue>&quot;Tentative&quot;</defaultValue>
    <description>Whether or not a claim with a &quot;root cause&quot;-flight which matches this proactivity should be eligible or not for EU261 compensation.</description>
    <inlineHelpText>Whether or not a claim with a &quot;root cause&quot;-flight which matches this proactivity should be eligible or not for EU261 compensation.</inlineHelpText>
    <label>EU261 Eligibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EU261_Eligibility</valueSetName>
    </valueSet>
</CustomField>

sas-core/main/default/objects/Proactivity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>For differentiating between the different types of proactivities</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Major Event</fullName>
            </value>
            <value>
                <fullName>Automatically Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sas-core/main/default/globalValueSets/EU261_Eligibility.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Tentative</fullName>
        <default>true</default>
        <label>Tentative</label>
    </customValue>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <description>Whether or not a passenger is, is not or might be eligible for EU261 compensation.</description>
    <masterLabel>EU261 Eligibility</masterLabel>
</GlobalValueSet>

sas-core/main/default/classes/services/ProactivityService_Test.cls
@IsTest
private class ProactivityService_Test {
  @IsTest
  public static void automationProactivitiesShouldBeCreated() {
    Flight__c f = new Flight__c(TEDS_Identifier__c = 'SK0001-20220817-ARN-UME');
    insert f;

    FlightIrregularities__c fi = new FlightIrregularities__c(
      Flight__c = f.Id,
      Code__c = 'DAMA',
      Reason__c = 'BIRDSTRIKE ON TAKEOFF FROM ARN'
    );
    insert fi;

    // Call the method being tested
    Test.startTest();
    ProactivityService.createAutomationProactivitiesFromFlightIds(
      new Set<Id>{ f.Id }
    );
    Test.stopTest();

    // Retrieve and verify the result
    List<Proactivity__c> proactiveRecords = [
      SELECT
        Id,
        Flight_Id__c,
        Note__c,
        Type__c,
        Automate_Matching_Claims__c,
        Eligibility_Explanation__c,
        EU261_Eligibility__c
      FROM Proactivity__c
    ];
    System.assertEquals(
      1,
      proactiveRecords.size(),
      'An incorrect number of Proactivity records were created'
    );
    Proactivity__c p = proactiveRecords[0];

    String flightId = Flight.TEDSIdToSimpleFlightIds(f.TEDS_Identifier__c)[0];

    System.assertEquals(flightId, p.Flight_Id__c, 'Incorrect flight id');
    System.assertEquals(
      'a bird strike on the aircraft assigned to your flight',
      p.Note__c,
      'Note should be "a bird strike on the aircraft assigned to your flight"'
    );
    System.assertEquals(
      'Automatically Created',
      p.Type__c,
      'Type should be "Automatically Created"'
    );
    System.assertEquals(
      false,
      p.Automate_Matching_Claims__c,
      'Automate Matching Claims should be true'
    );
    System.assertEquals(
      'a bird strike on the aircraft assigned to your flight',
      p.Eligibility_Explanation__c,
      'Eligibility explanation should be "a bird strike on the aircraft assigned to your flight"'
    );
    System.assertEquals(
      'No',
      p.EU261_Eligibility__c,
      'Should not be EU261 eligible'
    );
  }

  @IsTest
  public static void multiMatchIrregularityShouldNotGenerateAProactivity() {
    Flight__c f = new Flight__c(TEDS_Identifier__c = 'SK0001-20220817-ARN-UME');
    insert f;

    FlightIrregularities__c fi = new FlightIrregularities__c(
      Flight__c = f.Id,
      Code__c = 'DAMA',
      Reason__c = 'BIRDSTRIKE ON TAKEOFF DURING THUNDERSTORM'
    );
    insert fi;

    // Call the method being tested
    Test.startTest();
    ProactivityService.createAutomationProactivitiesFromFlightIds(
      new Set<Id>{ f.Id }
    );
    Test.stopTest();

    // Retrieve and verify the result
    List<Proactivity__c> proactiveRecords = [SELECT Id FROM Proactivity__c];
    System.assertEquals(
      0,
      proactiveRecords.size(),
      'No proactivity should have been created'
    );
  }
}